### ISSUE TITLE
Field Not Found Error

### ISSUE THREAD

**Issue by doomed2020** [AdvancedHacker101/android-c-sharp-rat-server#4]
Hi,

I copied the new files you pushed (sCore.dll, NAudio.dll, NAudio.xml and AndroidExtension.dll) in the Tutserver Debug folder, got some New and Fresh Errors on the startup.

![tutserver2](https://user-images.githubusercontent.com/863015/36902818-a01efde8-1e4d-11e8-918c-319d2a4dc5ff.png)

```
************** Exception Text **************
System.MissingFieldException: Field not found: 'sCore.IO.BridgeFunctions.ShowMessageBox'.
   at TutServer.Form1.ScriptHost.SetupBridge()
   at TutServer.Form1.Form1_Shown(Object sender, EventArgs e) in C:\Users\Doom\Downloads\C-Sharp-R.A.T-Server-master\C-Sharp-R.A.T-Server-master\TutServer\Form1.cs:line 1929
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

When I chose the Android Extension Plugin, I get another Error:
```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at sCore.Integration.Integrate.VerifyPermissions(Permissions permission, String pluginName)
   at sCore.Integration.Integrate.SetPlugin(IPluginMain iface, String previousToken)
   at AndroidExtension.Class1.Main()
   at TutServer.Form1.ScriptHost.ExecuteDll(String dllName) in C:\Users\Doom\Downloads\C-Sharp-R.A.T-Server-master\C-Sharp-R.A.T-Server-master\TutServer\Form1.cs:line 575
   at TutServer.Form1.button37_Click(Object sender, EventArgs e) in C:\Users\Doom\Downloads\C-Sharp-R.A.T-Server-master\C-Sharp-R.A.T-Server-master\TutServer\Form1.cs:line 5369
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by AdvancedHacker101** [comment]
Hi!  
It seems like you didn't change the TutServer.exe itself.  
I updated that too, since the function bridging algorithm got reworked, and the server needed to implement it in a new way. The old server implementiation points to a non-existing variable.  
I hope this solves your problem!

**Comment by doomed2020** [comment]
Ok, Fixed this issue by Compiling the new version of Tutserver,exe, Now got this error when the Client Connects : 

```
Application: TutServer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Sockets.SocketException
   at System.Net.Sockets.Socket.DoBind(System.Net.EndPoint, System.Net.SocketAddress)
   at System.Net.Sockets.Socket.Bind(System.Net.EndPoint)
   at AndroidExtension.Class1.PluginMain()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```
